name: eval
channels:
  - defaults
  - pog87
  - conda-forge
dependencies:
  - python=3.8
  - jupyter=1.0.0
  - pip=21.2
  - pip:
    - numpy==1.21.5
    - miseval==1.0.0
    - numba==0.55.2
    - nibabel==5.2.1
    - matplotlib==3.7.5
    - pandas==2.0.3
    - nilearn==0.10.4

