name: meld_classifier
channels:
  - defaults
  - pog87
  - conda-forge
dependencies:
	- _libgcc_mutex=0.1
	- _openmp_mutex=5.1
	- absl-py=2.1.0
	- aiohappyeyeballs=2.4.0
	- aiohttp=3.10.5
	- aiosignal=1.2.0
	- alibi=0.6.0
	- alsa-lib=1.2.8
	- annotated-types=0.7.0
	- anyio=3.5.0
	- aom=3.6.0
	- argon2-cffi=21.3.0
	- argon2-cffi-bindings=21.2.0
	- asttokens=2.0.5
	- astunparse=1.6.3
	- async-timeout=4.0.3
	- attr=2.5.1
	- attrs=21.4.0
	- babel=2.11.0
	- backcall=0.2.0
	- beautifulsoup4=4.12.3
	- blas=1.0
	- bleach=4.1.0
	- blinker=1.6.2
	- blis=0.7.11
	- blosc=1.21.3
	- bottleneck=1.3.7
	- brotli=1.0.9
	- brotli-bin=1.0.9
	- brotli-python=1.0.9
	- brunsli=0.1
	- bzip2=1.0.8
	- c-ares=1.19.1
	- ca-certificates=2025.6.15
	- cached-property=1.5.2
	- cachetools=4.2.4
	- cairo=1.16.0
	- catalogue=2.0.10
	- certifi=2024.8.30
	- cffi=1.17.1
	- cfitsio=3.470
	- charls=2.2.0
	- charset-normalizer=3.3.2
	- click=8.1.7
	- cloudpathlib=0.20.0
	- cloudpickle=3.0.0
	- colorama=0.4.6
	- comm=0.2.1
	- confection=0.1.5
	- contourpy=1.0.5
	- cryptography=43.0.0
	- cuda-version=11.8
	- cudatoolkit=11.8.0
	- cudnn=8.9.2.26
	- cycler=0.11.0
	- cymem=2.0.11
	- cython=3.0.11
	- cython-blis=0.7.9
	- cytoolz=0.12.2
	- dask-core=2023.4.1
	- dataclasses=0.8
	- dav1d=1.2.1
	- dbus=1.13.18
	- debugpy=1.6.7
	- decorator=5.1.1
	- defusedxml=0.7.1
	- dill=0.3.9
	- executing=0.8.3
	- expat=2.7.1
	- fftw=3.3.10
	- filelock=3.16.1
	- flatbuffers=22.12.06
	- font-ttf-dejavu-sans-mono=2.37
	- font-ttf-inconsolata=2.001
	- font-ttf-source-code-pro=2.030
	- font-ttf-ubuntu=0.83
	- fontconfig=2.14.2
	- fonts-anaconda=1
	- fonts-conda-ecosystem=1
	- fonttools=4.51.0
	- fpdf=1.7.2
	- freetype=2.13.3
	- frozenlist=1.4.0
	- fsspec=2024.6.1
	- gast=0.3.3
	- gettext=0.24.1
	- gettext-tools=0.24.1
	- giflib=5.2.2
	- glib=2.78.4
	- glib-tools=2.78.4
	- gmp=6.3.0
	- google-auth=1.35.0
	- google-auth-oauthlib=0.4.4
	- google-pasta=0.2.0
	- graphite2=1.3.14
	- grpcio=1.51.1
	- gst-plugins-base=1.22.0
	- gstreamer=1.22.0
	- gstreamer-orc=0.4.41
	- h5py=2.10.0
	- harfbuzz=6.0.0
	- hdf5=1.10.6
	- hf-xet=1.1.5
	- huggingface-hub=0.33.0
	- icu=70.1
	- idna=3.7
	- imagecodecs=2021.8.26
	- imageio=2.33.1
	- importlib-metadata=7.0.1
	- importlib-resources=6.4.0
	- importlib_metadata=7.0.1
	- importlib_resources=6.4.0
	- iniconfig=1.1.1
	- intel-openmp=2023.1.0
	- ipykernel=6.29.5
	- ipython=8.12.2
	- ipython_genutils=0.2.0
	- jack=1.9.22
	- jedi=0.19.1
	- jinja2=3.1.4
	- joblib=1.4.2
	- jpeg=9e
	- json5=0.9.6
	- jsonschema=4.23.0
	- jsonschema-specifications=2023.7.1
	- jupyter_client=8.6.0
	- jupyter_core=5.7.2
	- jupyter_server=1.23.4
	- jupyterlab=3.2.9
	- jupyterlab_pygments=0.2.2
	- jupyterlab_server=2.27.3
	- jxrlib=1.1
	- keras=2.11.0
	- keras-preprocessing=1.1.2
	- kiwisolver=1.4.4
	- krb5=1.20.1
	- lame=3.100
	- langcodes=3.4.1
	- language-data=1.3.0
	- lapy=0.2
	- lcms2=2.16
	- ld_impl_linux-64=2.40
	- lerc=3.0
	- libabseil=20220623.0
	- libaec=1.1.3
	- libasprintf=0.24.1
	- libasprintf-devel=0.24.1
	- libavif=0.11.1
	- libblas=3.9.0
	- libbrotlicommon=1.0.9
	- libbrotlidec=1.0.9
	- libbrotlienc=1.0.9
	- libcap=2.66
	- libcblas=3.9.0
	- libclang=15.0.7
	- libclang13=15.0.7
	- libcups=2.3.3
	- libcurl=8.12.1
	- libdb=6.2.32
	- libdeflate=1.17
	- libedit=3.1.20230828
	- libev=4.33
	- libevent=2.1.10
	- libffi=3.4.4
	- libflac=1.4.3
	- libgcc=15.1.0
	- libgcc-ng=15.1.0
	- libgcrypt=1.11.1
	- libgcrypt-devel=1.11.1
	- libgcrypt-lib=1.11.1
	- libgcrypt-tools=1.11.1
	- libgettextpo=0.24.1
	- libgettextpo-devel=0.24.1
	- libgfortran-ng=11.2.0
	- libgfortran5=11.2.0
	- libglib=2.78.4
	- libgomp=15.1.0
	- libgpg-error=1.55
	- libgrpc=1.51.1
	- libiconv=1.18
	- liblapack=3.9.0
	- libllvm15=15.0.7
	- libnghttp2=1.57.0
	- libogg=1.3.5
	- libopus=1.3.1
	- libpng=1.6.39
	- libpq=15.2
	- libprotobuf=3.21.12
	- libsndfile=1.2.2
	- libsodium=1.0.18
	- libsqlite=3.46.0
	- libssh2=1.11.1
	- libstdcxx=15.1.0
	- libstdcxx-ng=15.1.0
	- libsystemd0=252
	- libtiff=4.5.1
	- libtool=2.4.7
	- libudev1=253
	- libuuid=2.38.1
	- libvorbis=1.3.7
	- libwebp=1.2.4
	- libwebp-base=1.2.4
	- libxcb=1.13
	- libxkbcommon=1.5.0
	- libxml2=2.10.3
	- libzlib=1.2.13
	- libzopfli=1.0.3
	- locket=1.0.0
	- lz4-c=1.9.4
	- marisa-trie=1.2.1
	- markdown=3.4.1
	- markdown-it-py=3.0.0
	- markupsafe=2.1.3
	- matplotlib=3.5.1
	- matplotlib-inline=0.1.6
	- matplotlib-surface-plotting=0.12
	- mdurl=0.1.2
	- meld-classifier=1.1.2
	- metis=5.1.0
	- mistune=2.0.4
	- mkl=2023.1.0
	- mkl-service=2.4.0
	- mkl_fft=1.3.8
	- mkl_random=1.2.4
	- mpfr=4.2.1
	- mpg123=1.32.9
	- multidict=6.0.4
	- murmurhash=1.0.13
	- mysql-common=8.0.32
	- mysql-libs=8.0.32
	- narwhals=1.42.1
	- nbclassic=0.5.5
	- nbclient=0.8.0
	- nbconvert=7.16.4
	- nbformat=5.10.4
	- nccl=2.27.3.1
	- ncurses=6.4
	- nest-asyncio=1.6.0
	- networkx=3.1
	- neurocombat=0.2.12
	- nibabel=3.2.2
	- nilearn=0.8.0
	- notebook-shim=0.2.3
	- nspr=4.35
	- nss=3.89.1
	- numexpr=2.8.4
	- numpy=1.21.0
	- oauthlib=3.2.2
	- olefile=0.46
	- openjpeg=2.5.2
	- openssl=3.1.8
	- opt_einsum=3.3.0
	- packaging=24.1
	- pandas=1.5.3
	- pandocfilters=1.5.0
	- parso=0.8.3
	- partd=1.4.1
	- pathy=0.10.2
	- patsy=0.5.2
	- pcre2=10.42
	- pexpect=4.8.0
	- pickleshare=0.7.5
	- pillow=8.4.0
	- pixman=0.40.0
	- pkgutil-resolve-name=1.3.10
	- platformdirs=3.10.0
	- plotly=6.1.2
	- pluggy=1.0.0
	- ply=3.11
	- pooch=1.7.0
	- potpourri3d=0.0.4
	- preshed=3.0.10
	- prometheus_client=0.14.1
	- prompt-toolkit=3.0.43
	- protobuf=4.21.12
	- psutil=5.9.0
	- ptitprince=0.2.3
	- ptyprocess=0.7.0
	- pulseaudio=16.1
	- pure_eval=0.2.2
	- py=1.11.0
	- pyasn1=0.4.8
	- pyasn1-modules=0.2.8
	- pycparser=2.21
	- pydantic=2.10.6
	- pydantic-core=2.27.2
	- pydicom=2.4.4
	- pygments=2.15.1
	- pyhamcrest=1.9.0
	- pyjwt=2.8.0
	- pyopenssl=24.2.1
	- pyparsing=3.0.9
	- pyqt=5.15.10
	- pyqt5-sip=12.13.0
	- pysocks=1.7.1
	- pytest=6.2.5
	- python=3.8.20
	- python-dateutil=2.9.0post0
	- python-fastjsonschema=2.16.2
	- python-flatbuffers=24.3.25
	- python-tzdata=2025.2
	- python_abi=3.8
	- pytz=2024.1
	- pywavelets=1.4.1
	- pyyaml=6.0.2
	- pyzmq=25.1.2
	- qt-main=5.15.8
	- re2=2023.02.01
	- readline=8.2
	- referencing=0.30.2
	- regex=2024.11.6
	- requests=2.32.3
	- requests-oauthlib=2.0.0
	- rich=14.0.0
	- rpds-py=0.10.6
	- rsa=4.7.2
	- safetensors=0.5.3
	- scikit-image=0.18.3
	- scikit-learn=0.24.2
	- scikit-sparse=0.4.6
	- scipy=1.4.1
	- seaborn=0.13.2
	- send2trash=1.8.2
	- setuptools=75.1.0
	- shellingham=1.5.4
	- simpleitk=2.1.1
	- sip=6.7.12
	- six=1.16.0
	- smart-open=7.1.0
	- smart_open=5.2.1
	- snappy=1.1.10
	- sniffio=1.3.0
	- soupsieve=2.5
	- spacy=3.7.5
	- spacy-legacy=3.0.12
	- spacy-loggers=1.0.5
	- spacy-lookups-data=1.0.5
	- sqlite=3.45.3
	- srsly=2.4.8
	- stack_data=0.2.0
	- suitesparse=5.10.1
	- tbb=2021.8.0
	- tensorboard=2.2.2
	- tensorboard-data-server=0.6.1
	- tensorboard-plugin-wit=1.8.1
	- tensorflow=2.2.0
	- tensorflow-estimator=2.2.0
	- termcolor=2.1.0
	- terminado=0.17.1
	- thinc=8.2.5
	- threadpoolctl=3.5.0
	- tifffile=2021.11.2
	- tinycss2=1.2.1
	- tk=8.6.14
	- tokenizers=0.20.3
	- toml=0.10.2
	- tomli=2.0.1
	- toolz=0.12.0
	- torch=1.12.0
	- torchvision=0.13.0
	- tornado=6.4.1
	- tqdm=4.67.1
	- traitlets=5.14.3
	- transformers=4.46.3
	- typer=0.16.0
	- typing-extensions=4.13.2
	- unicodedata2=15.1.0
	- urllib3=2.2.3
	- wasabi=1.1.3
	- wcwidth=0.2.5
	- weasel=0.4.1
	- webencodings=0.5.1
	- websocket-client=1.8.0
	- werkzeug=3.0.3
	- wheel=0.44.0
	- wrapt=1.14.1
	- xcb-util=0.4.0
	- xcb-util-image=0.4.0
	- xcb-util-keysyms=0.4.0
	- xcb-util-renderutil=0.3.9
	- xcb-util-wm=0.4.1
	- xkeyboard-config=2.38
	- xorg-kbproto=1.0.7
	- xorg-libice=1.1.2
	- xorg-libsm=1.2.6
	- xorg-libx11=1.8.4
	- xorg-libxext=1.3.4
	- xorg-libxrender=0.9.10
	- xorg-renderproto=0.11.1
	- xorg-xextproto=7.3.0
	- xorg-xorgproto=2024.1
	- xorg-xproto=7.0.31
	- xz=5.6.4
	- yaml=0.2.5
	- yarl=1.11.0
	- zeromq=4.3.5
	- zfp=0.5.5
	- zipp=3.20.2
	- zlib=1.2.13
	- zstd=1.5.6
	- pip=21.2.4
	- pip:
		- absl-py==2.1.0
		- aiohappyeyeballs==2.4.0
		- aiohttp==3.10.5
		- aiosignal==1.2.0
		- alibi==0.6.0
		- annotated-types==0.7.0
		- anyio==3.5.0
		- argon2-cffi==21.3.0
		- argon2-cffi-bindings==21.2.0
		- asttokens==2.0.5
		- astunparse==1.6.3
		- async-timeout==4.0.3
		- attrs==21.4.0
		- Babel==2.11.0
		- backcall==0.2.0
		- beautifulsoup4==4.12.3
		- bleach==4.1.0
		- blinker==1.6.2
		- blis==0.7.11
		- Bottleneck==1.3.7
		- Brotli==1.0.9
		- cached-property==1.5.2
		- cachetools==4.2.4
		- catalogue==2.0.10
		- certifi==2024.8.30
		- cffi==1.17.1
		- charset-normalizer==3.3.2
		- click==8.1.7
		- cloudpathlib==0.20.0
		- cloudpickle==3.0.0
		- colorama==0.4.6
		- comm==0.2.1
		- confection==0.1.5
		- contourpy==1.0.5
		- cryptography==43.0.0
		- cycler==0.11.0
		- cymem==2.0.11
		- Cython==3.0.11
		- cytoolz==0.12.2
		- dask==2023.4.1
		- dataclasses==0.8
		- debugpy==1.6.7
		- decorator==5.1.1
		- defusedxml==0.7.1
		- dill==0.3.9
		- executing==0.8.3
		- fastjsonschema==2.16.2
		- filelock==3.16.1
		- flatbuffers==24.3.25
		- fonttools==4.51.0
		- fpdf==1.7.2
		- frozenlist==1.4.0
		- fsspec==2024.6.1
		- gast==0.3.3
		- google-auth==1.35.0
		- google-auth-oauthlib==0.4.4
		- google-pasta==0.2.0
		- grpcio==1.51.1
		- h5py==2.10.0
		- hf-xet==1.1.5
		- huggingface-hub==0.33.0
		- idna==3.7
		- imagecodecs==2021.8.26
		- imageio==2.33.1
		- importlib-metadata==7.0.1
		- importlib_resources==6.4.0
		- iniconfig==1.1.1
		- ipykernel==6.29.5
		- ipython==8.12.2
		- ipython-genutils==0.2.0
		- jedi==0.19.1
		- Jinja2==3.1.4
		- joblib==1.4.2
		- json5==0.9.6
		- jsonschema==4.23.0
		- jsonschema-specifications==2023.7.1
		- jupyter_client==8.6.0
		- jupyter_core==5.7.2
		- jupyter-server==1.23.4
		- jupyterlab==3.2.9
		- jupyterlab-pygments==0.2.2
		- jupyterlab_server==2.27.3
		- keras==2.11.0
		- Keras-Preprocessing==1.1.2
		- kiwisolver==1.4.4
		- langcodes==3.4.1
		- language_data==1.3.0
		- git+https://github.com/Deep-MI/LaPy.git@0.3
		- locket==1.0.0
		- marisa-trie==1.2.1
		- Markdown==3.4.1
		- markdown-it-py==3.0.0
		- MarkupSafe==2.1.3
		- matplotlib==3.5.1
		- matplotlib-inline==0.1.6
		- matplotlib-surface-plotting==0.12
		- mdurl==0.1.2
		- meld_classifier==1.1.2=/home/guenael/git/Stage/research_epilepsy/Code/meld_classifier
		- mistune==2.0.4
		- mkl-fft==1.3.8
		- mkl-random==1.2.4
		- mkl-service==2.4.0
		- multidict==6.0.4
		- murmurhash==1.0.13
		- narwhals==1.42.1
		- nbclassic==0.5.5
		- nbclient==0.8.0
		- nbconvert==7.16.4
		- nbformat==5.10.4
		- nest-asyncio==1.6.0
		- networkx==3.1
		- neuroCombat==0.2.12
		- nibabel==3.2.2
		- nilearn==0.8.0
		- notebook_shim==0.2.3
		- numexpr==2.8.4
		- numpy==1.21.0
		- oauthlib==3.2.2
		- olefile==0.46
		- opt-einsum==3.3.0
		- packaging==24.1
		- pandas==2.0.0
		- pandocfilters==1.5.0
		- parso==0.8.3
		- partd==1.4.1
		- pathy==0.10.2
		- patsy==0.5.2
		- pexpect==4.8.0
		- pickleshare==0.7.5
		- Pillow==8.4.0
		- pkgutil_resolve_name==1.3.10
		- platformdirs==3.10.0
		- plotly==6.1.2
		- pluggy==1.0.0
		- ply==3.11
		- pooch==1.7.0
		- potpourri3d==0.0.4
		- preshed==3.0.10
		- prometheus-client==0.14.1
		- prompt-toolkit==3.0.43
		- protobuf==4.21.12
		- psutil==5.9.0
		- ptitprince==0.2.3
		- ptyprocess==0.7.0
		- pure-eval==0.2.2
		- py==1.11.0
		- pyasn1==0.4.8
		- pyasn1-modules==0.2.8
		- pycparser==2.21
		- pydantic==2.10.6
		- pydantic_core==2.27.2
		- pydicom==2.4.4
		- Pygments==2.15.1
		- PyHamcrest==1.9.0
		- PyJWT==2.8.0
		- pyOpenSSL==24.2.1
		- pyparsing==3.0.9
		- PyQt5==5.15.10
		- PyQt5-sip==12.13.0
		- PySocks==1.7.1
		- pytest==6.2.5
		- python-dateutil==2.9.0.post0
		- pytz==2024.1
		- PyWavelets==1.4.1
		- PyYAML==6.0.2
		- pyzmq==25.1.2
		- referencing==0.30.2
		- regex==2024.11.6
		- requests==2.32.3
		- requests-oauthlib==2.0.0
		- rich==14.0.0
		- rpds-py==0.10.6
		- rsa==4.7.2
		- safetensors==0.5.3
		- scikit-image==0.18.3
		- scikit-learn==0.24.2
		- scikit-sparse==0.4.6
		- scipy==1.4.1
		- seaborn==0.13.2
		- Send2Trash==1.8.2
		- setuptools==75.1.0
		- shellingham==1.5.4
		- SimpleITK==2.1.1
		- sip==6.7.12
		- six==1.16.0
		- smart-open==7.1.0
		- sniffio==1.3.0
		- soupsieve==2.5
		- spacy==3.7.5
		- spacy-legacy==3.0.12
		- spacy-loggers==1.0.5
		- spacy-lookups-data==1.0.5
		- srsly==2.4.8
		- stack-data==0.2.0
		- tensorboard==2.2.2
		- tensorboard-data-server==0.6.1
		- tensorboard-plugin-wit==1.8.1
		- tensorflow==2.2.0
		- tensorflow-estimator==2.2.0
		- termcolor==2.1.0
		- terminado==0.17.1
		- thinc==8.2.5
		- threadpoolctl==3.5.0
		- tifffile==2021.11.2
		- tinycss2==1.2.1
		- tokenizers==0.20.3
		- toml==0.10.2
		- tomli==2.0.1
		- toolz==0.12.0
		- torch==1.12.0
		- torchvision==0.13.0
		- tornado==6.4.1
		- tqdm==4.67.1
		- traitlets==5.14.3
		- transformers==4.46.3
		- typer==0.16.0
		- typing_extensions==4.13.2
		- tzdata==2025.2
		- unicodedata2==15.1.0
		- urllib3==2.2.3
		- wasabi==1.1.3
		- wcwidth==0.2.5
		- weasel==0.4.1
		- webencodings==0.5.1
		- websocket-client==1.8.0
		- Werkzeug==3.0.3
		- wheel==0.44.0
		- wrapt==1.14.1
		- yarl==1.11.0
		- zipp==3.20.2
